# Generated by Django 4.1.4 on 2023-04-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
