# Generated by Django 4.1.4 on 2023-05-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_adoption_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='adapost',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
