# Generated by Django 4.1.4 on 2023-05-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0003_adoption_adapost'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='user',
            field=models.CharField(db_index=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoption',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
